# Generated by Django 5.2.7 on 2026-07-30 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_user_options'),
        ('students', '0006_discount_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_opens_at', models.TimeField(default='07:30', verbose_name='ouverture')),
                ('late_after', models.TimeField(default='08:15', help_text='Une entrée après cette heure est comptée comme un retard.', verbose_name='retard au-delà de')),
                ('school_closes_at', models.TimeField(default='17:30', verbose_name='fermeture')),
                ('notify_parent_on_entry', models.BooleanField(default=False, help_text='Un SMS par entrée et par élève : à activer en connaissance du coût.', verbose_name="prévenir le parent à l'entrée")),
                ('notify_parent_on_exit', models.BooleanField(default=False, verbose_name='prévenir le parent à la sortie')),
                ('notify_parent_on_absence', models.BooleanField(default=True, verbose_name="prévenir le parent en cas d'absence")),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': "paramètres d'assiduité",
                'verbose_name_plural': "paramètres d'assiduité",
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=3, verbose_name='sens')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='horodatage')),
                ('day', models.DateField(db_index=True, editable=False, help_text="Dérivée de l'horodatage, pour regrouper sans calcul de fuseau.", verbose_name='journée')),
                ('source', models.CharField(choices=[('QR', 'QR code'), ('MANUAL', 'Saisie manuelle')], default='QR', max_length=10)),
                ('recorded_by', models.CharField(blank=True, max_length=150, verbose_name='enregistré par')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='remarque')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='anomalie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='students.student')),
            ],
            options={
                'verbose_name': 'passage',
                'verbose_name_plural': 'passages',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['school', 'day', 'student'], name='attendance__school__a72e59_idx'), models.Index(fields=['school', 'student', 'occurred_at'], name='attendance__school__8a8b9d_idx')],
            },
        ),
    ]
