# Generated by Django 5.2.7 on 2026-07-30 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesettings',
            name='late_after',
            field=models.TimeField(default=datetime.time(8, 15), help_text='Une entrée après cette heure est comptée comme un retard.', verbose_name='retard au-delà de'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='school_closes_at',
            field=models.TimeField(default=datetime.time(17, 30), verbose_name='fermeture'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='school_opens_at',
            field=models.TimeField(default=datetime.time(7, 30), verbose_name='ouverture'),
        ),
    ]
