# Generated by Django 5.2.7 on 2026-07-29 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='téléphone normalisé')),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'code de connexion',
                'verbose_name_plural': 'codes de connexion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'phone', 'consumed_at'], name='notificatio_school__cfaba7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReminderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('UPCOMING', 'Échéance à venir'), ('ARREARS', 'Arriérés')], max_length=15)),
                ('period', models.DateField(verbose_name='période visée')),
                ('run_date', models.DateField(default=django.utils.timezone.localdate, verbose_name="date d'exécution")),
                ('sent', models.PositiveIntegerField(default=0, verbose_name='envoyés')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='échecs')),
                ('skipped', models.PositiveIntegerField(default=0, verbose_name='ignorés')),
                ('simulated', models.BooleanField(default=False, verbose_name='mode simulation')),
                ('triggered_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'campagne de rappels',
                'verbose_name_plural': 'campagnes de rappels',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'kind', 'period', 'run_date'), name='one_reminder_run_per_day')],
            },
        ),
    ]
