# Generated by Django 5.2.7 on 2026-07-29 16:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(editable=False, max_length=10, verbose_name='matricule')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom(s)')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('cni', models.CharField(blank=True, max_length=30, verbose_name='CNI')),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Célibataire'), ('MARRIED', 'Marié(e)'), ('DIVORCED', 'Divorcé(e)'), ('WIDOWED', 'Veuf / Veuve')], max_length=10, verbose_name='situation matrimoniale')),
                ('corps', models.CharField(blank=True, max_length=100, verbose_name='corps')),
                ('grade', models.CharField(blank=True, max_length=100, verbose_name='grade / génération')),
                ('academic_diploma', models.CharField(blank=True, max_length=150, verbose_name='diplôme académique')),
                ('professional_diploma', models.CharField(blank=True, max_length=150, verbose_name='diplôme professionnel')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name="entrée dans l'enseignement")),
                ('specialty', models.CharField(blank=True, max_length=150, verbose_name='spécialité')),
                ('function', models.CharField(blank=True, max_length=150, verbose_name='fonction')),
                ('service_start_date', models.DateField(blank=True, null=True, verbose_name="prise de service dans l'établissement")),
                ('courses_taught', models.CharField(blank=True, max_length=255, verbose_name='cours tenu(s)')),
                ('class_type', models.CharField(blank=True, max_length=100, verbose_name='type de classe')),
                ('students_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='effectifs')),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'CDI'), ('FIXED_TERM', 'CDD'), ('SUBSTITUTE', 'Vacataire')], default='PERMANENT', max_length=15, verbose_name='type de contrat')),
                ('is_active', models.BooleanField(default=True, verbose_name='en activité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'enseignant',
                'verbose_name_plural': 'enseignants',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='A, B, C…', max_length=10, verbose_name='code')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='libellé')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='rang')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('teacher', models.ForeignKey(blank=True, help_text='Facultatif — renseigné si la rubrique correspond à un employé identifié.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_rubrics', to='staff.teacher')),
            ],
            options={
                'verbose_name': 'rubrique salariale',
                'verbose_name_plural': 'rubriques salariales',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRaise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name="date d'effet")),
                ('previous_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant précédent')),
                ('new_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nouveau montant')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('approved_by', models.CharField(blank=True, max_length=150, verbose_name='approuvé par')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raises', to='staff.teacher')),
            ],
            options={
                'verbose_name': 'augmentation',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LEAVE', 'Congé'), ('SICK', 'Maladie'), ('UNPAID', 'Absence non rémunérée'), ('OTHER', 'Autre')], max_length=10, verbose_name='nature')),
                ('start_date', models.DateField(verbose_name='du')),
                ('end_date', models.DateField(verbose_name='au')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='staff.teacher')),
            ],
            options={
                'verbose_name': 'absence',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'CDI'), ('FIXED_TERM', 'CDD'), ('SUBSTITUTE', 'Vacataire')], max_length=15)),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('gross_salary', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='salaire brut')),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='document')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='staff.teacher')),
            ],
            options={
                'verbose_name': 'contrat',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Dernier jour du mois concerné.', verbose_name='période')),
                ('gross_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='brut')),
                ('social_contributions', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cotisations sociales')),
                ('other_deductions', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='autres retenues')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='core.schoolyear')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='staff.salaryrubric')),
            ],
            options={
                'verbose_name': 'salaire',
                'verbose_name_plural': 'salaires',
                'ordering': ['period', 'rubric__order'],
                'indexes': [models.Index(fields=['school', 'year', 'period'], name='staff_salar_school__23484f_idx')],
                'constraints': [models.UniqueConstraint(fields=('rubric', 'period'), name='unique_salary_per_rubric_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('school', 'matricule'), name='unique_matricule_per_school'),
        ),
        migrations.AddConstraint(
            model_name='salaryrubric',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_rubric_per_school'),
        ),
    ]
