# Generated by Django 5.2.7 on 2026-07-29 17:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='salaire de base mensuel')),
                ('taxable_bonus', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='primes imposables')),
                ('non_taxable_allowance', models.PositiveIntegerField(default=0, help_text="Transport et assimilés, dans la limite d'exonération légale.", validators=[django.core.validators.MinValueValidator(0)], verbose_name='indemnités non imposables')),
                ('is_executive', models.BooleanField(default=False, help_text='Assujettit au régime complémentaire IPRES cadres.', verbose_name='cadre')),
                ('family_shares', models.CharField(choices=[('1', '1 part'), ('1.5', '1,5 part'), ('2', '2 parts'), ('2.5', '2,5 parts'), ('3', '3 parts'), ('3.5', '3,5 parts'), ('4', '4 parts'), ('4.5', '4,5 parts'), ('5', '5 parts')], default='1', max_length=4, verbose_name='parts fiscales')),
                ('social_security_number', models.CharField(blank=True, max_length=40, verbose_name='n° de sécurité sociale')),
                ('bank_account', models.CharField(blank=True, max_length=40, verbose_name='compte bancaire')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='staff.teacher')),
            ],
            options={
                'verbose_name': 'profil de paie',
                'verbose_name_plural': 'profils de paie',
                'ordering': ['teacher__matricule'],
            },
        ),
        migrations.CreateModel(
            name='PayrollScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Par exemple : Barème 2026', max_length=100, verbose_name='libellé')),
                ('effective_from', models.DateField(verbose_name='applicable à partir du')),
                ('values', models.JSONField(default=dict, verbose_name='barèmes')),
                ('validated_by', models.CharField(blank=True, help_text='Expert-comptable ayant vérifié les taux. Vide = non validé.', max_length=150, verbose_name='validé par')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'barème de paie',
                'verbose_name_plural': 'barèmes de paie',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Dernier jour du mois concerné.', verbose_name='période')),
                ('gross', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='brut imposable')),
                ('non_taxable', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='indemnités non imposables')),
                ('employee_contributions', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cotisations salariales')),
                ('employer_contributions', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='charges patronales')),
                ('income_tax', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='impôt sur le revenu')),
                ('trimf', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TRIMF')),
                ('other_deductions', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='autres retenues')),
                ('net_pay', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='net à payer')),
                ('computation', models.JSONField(default=dict, verbose_name='détail du calcul')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='payé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='staff.payrollscale')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='staff.teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'bulletin de paie',
                'verbose_name_plural': 'bulletins de paie',
                'ordering': ['-period', 'teacher__matricule'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollscale',
            constraint=models.UniqueConstraint(fields=('school', 'effective_from'), name='unique_scale_per_date'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['school', 'year', 'period'], name='staff_paysl_school__0b4e0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('teacher', 'period'), name='one_payslip_per_teacher_period'),
        ),
    ]
