# Generated by Django 5.2.7 on 2026-07-29 16:03

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(default='SN', max_length=2, verbose_name='pays')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('TRIAL', 'Essai'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='TRIAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('PAST_DUE', 'Impayé'), ('SUSPENDED', 'Suspendu'), ('CANCELLED', 'Résilié')], default='ACTIVE', max_length=20)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('max_students', models.PositiveIntegerField(default=100, help_text="Plafond d'effectif inclus dans le plan.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'abonnement',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super administrateur'), ('ADMIN', "Administrateur d'établissement"), ('ACCOUNTANT', 'Comptable / Trésorier'), ('SECRETARY', 'Secrétaire'), ('TEACHER', 'Enseignant'), ('PARENT', 'Parent')], default='SECRETARY', max_length=20, verbose_name='rôle')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('school', models.ForeignKey(blank=True, help_text='Nul uniquement pour le super-administrateur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.school')),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
            managers=[
                ('objects', apps.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255, verbose_name='destinataire')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('template', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échec')], default='PENDING', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school', to='core.subscription'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_label', models.CharField(blank=True, help_text="Identité figée au moment de l'action.", max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('EXPORT', 'Export')], max_length=10)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.school')),
            ],
            options={
                'verbose_name': "entrée d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['school', 'entity', 'entity_id'], name='core_auditl_school__12d499_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Par exemple : 2025/2026', max_length=20, verbose_name='libellé')),
                ('start_date', models.DateField(verbose_name="début de l'exercice")),
                ('end_date', models.DateField(verbose_name="fin de l'exercice")),
                ('tuition_months', models.PositiveSmallIntegerField(default=9, verbose_name='nombre de mois de mensualité')),
                ('is_current', models.BooleanField(default=False, verbose_name='année courante')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('school', 'label'), name='unique_year_label_per_school'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('school',), name='one_current_year_per_school')],
            },
        ),
    ]
