# Generated by Django 5.2.7 on 2026-07-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'email'], 'verbose_name': 'utilisateur'},
        ),
    ]
