# Generated by Django 5.2.7 on 2026-08-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_photo_loginsession_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="Posé sur les comptes créés à l'ouverture d'un établissement. Tant qu'il est vrai, le compte ne peut rien faire d'autre que changer son mot de passe.", verbose_name='mot de passe à renouveler'),
        ),
    ]
