# Generated by Django 5.2.7 on 2026-07-29 16:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='code')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='rang')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('monthly_budget', models.PositiveIntegerField(blank=True, help_text='Sert au comparatif prévu / réalisé.', null=True, verbose_name='budget mensuel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'rubrique de charge',
                'verbose_name_plural': 'rubriques de charge',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(verbose_name="date d'opération")),
                ('period', models.DateField(db_index=True, editable=False, verbose_name='période')),
                ('label', models.CharField(max_length=255, verbose_name='intitulé')),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant')),
                ('channel', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('TRANSFER', 'Virement'), ('CHECK', 'Chèque')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_incomes', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'autre produit',
                'verbose_name_plural': 'autres produits',
                'ordering': ['-operation_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='intitulé')),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant')),
                ('channel', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('TRANSFER', 'Virement'), ('CHECK', 'Chèque')], default='TRANSFER', max_length=20)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, verbose_name='jour du mois')),
                ('start_date', models.DateField(verbose_name='à partir du')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name="jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='finance.expensecategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'dépense récurrente',
                'verbose_name_plural': 'dépenses récurrentes',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(verbose_name="date d'opération")),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='date de paiement')),
                ('period', models.DateField(db_index=True, editable=False, verbose_name='période')),
                ('channel', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('TRANSFER', 'Virement'), ('CHECK', 'Chèque')], default='CASH', max_length=20, verbose_name='canal')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='n° de facture')),
                ('label', models.CharField(max_length=255, verbose_name='intitulé')),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant')),
                ('transfer_fee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='frais de transfert')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='justificatif')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente de validation'), ('APPROVED', 'Validée'), ('REJECTED', 'Rejetée')], default='APPROVED', max_length=10, verbose_name='statut')),
                ('approved_by', models.CharField(blank=True, max_length=150, verbose_name='validée par')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='validée le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.schoolyear')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='rubrique')),
                ('recurring_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated', to='finance.recurringexpense')),
            ],
            options={
                'verbose_name': 'dépense',
                'verbose_name_plural': 'dépenses',
                'ordering': ['-operation_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_category_per_school'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['school', 'year', 'period', 'category'], name='finance_exp_school__67115e_idx'),
        ),
    ]
