# Generated by Django 5.2.7 on 2026-07-30 13:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_user_options'),
        ('staff', '0003_teacher_address_teacher_email_and_more'),
        ('students', '0006_discount_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1, verbose_name='coefficient')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='rang')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='students.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('teacher', models.ForeignKey(blank=True, help_text='Enseignant autorisé à saisir les notes de cette matière.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='staff.teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'matière de classe',
                'verbose_name_plural': 'matières de classe',
                'ordering': ['order', 'subject__order'],
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Par exemple : 1er trimestre', max_length=120, verbose_name='intitulé')),
                ('kind', models.CharField(choices=[('TERM', 'Composition trimestrielle'), ('FREE', 'Évaluation libre')], default='TERM', max_length=6, verbose_name='nature')),
                ('term', models.PositiveSmallIntegerField(blank=True, help_text='1, 2 ou 3 pour une composition trimestrielle.', null=True, verbose_name='trimestre')),
                ('date', models.DateField(verbose_name="date de l'évaluation")),
                ('status', models.CharField(choices=[('DRAFT', 'En préparation'), ('OPEN', 'Saisie ouverte'), ('CLOSED', 'Clôturée')], default='DRAFT', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compositions', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'composition',
                'verbose_name_plural': 'compositions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GradeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False, verbose_name='validée')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by', models.CharField(blank=True, max_length=150)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='academics.classsubject')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='academics.composition')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'feuille de notes',
                'verbose_name_plural': 'feuilles de notes',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text="Sur 20. Vide signifie « absent », ce qui n'est pas un zéro.", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))], verbose_name='note')),
                ('is_absent', models.BooleanField(default=False, verbose_name='absent')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='appréciation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.gradesheet')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school-logos/', verbose_name='logo')),
                ('header_line_1', models.CharField(blank=True, help_text='Par exemple : République du Sénégal', max_length=120, verbose_name="première ligne d'en-tête")),
                ('header_line_2', models.CharField(blank=True, help_text="Par exemple : Ministère de l'Éducation nationale", max_length=120, verbose_name="deuxième ligne d'en-tête")),
                ('header_line_3', models.CharField(blank=True, help_text="Par exemple : Inspection de l'Éducation et de la Formation de Dakar", max_length=120, verbose_name="troisième ligne d'en-tête")),
                ('establishment_code', models.CharField(blank=True, max_length=40, verbose_name='code établissement')),
                ('principal_name', models.CharField(blank=True, max_length=120, verbose_name='nom du directeur')),
                ('principal_title', models.CharField(blank=True, default='Le Directeur', max_length=80, verbose_name='fonction')),
                ('show_rank', models.BooleanField(default=True, verbose_name='afficher le rang')),
                ('show_class_average', models.BooleanField(default=True, verbose_name='afficher la moyenne de classe')),
                ('footer_note', models.TextField(blank=True, verbose_name='mention de pied')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'paramètres du bulletin',
                'verbose_name_plural': 'paramètres du bulletin',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='intitulé')),
                ('default_coefficient', models.PositiveSmallIntegerField(default=1, verbose_name='coefficient par défaut')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='rang')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='composition',
            constraint=models.UniqueConstraint(fields=('school', 'year', 'name'), name='unique_composition_name_per_year'),
        ),
        migrations.AddConstraint(
            model_name='gradesheet',
            constraint=models.UniqueConstraint(fields=('composition', 'class_subject'), name='unique_sheet_per_composition'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('sheet', 'student'), name='unique_grade_per_sheet_student'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_absent', True), ('value__isnull', True)), ('is_absent', False), _connector='OR'), name='absent_grade_has_no_value'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_subject_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('classroom', 'subject', 'year'), name='unique_class_subject_per_year'),
        ),
    ]
