# Generated by Django 5.2.7 on 2026-07-31 18:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubject',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='default_coefficient',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=10, help_text="Note maximale de la matière. C'est elle qui fait son poids.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='barème'),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='max_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Laisser vide pour reprendre le barème de la classe.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="barème de l'épreuve"),
        ),
        migrations.AddField(
            model_name='subject',
            name='default_max_score',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='barème par défaut'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Sur le barème de la feuille, et non sur 20. Vide signifie « absent », ce qui n'est pas un zéro.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='note'),
        ),
    ]
