# Generated by Django 5.2.7 on 2026-08-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_classsubject_coefficient_and_more'),
        ('staff', '0003_teacher_address_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text="Intervenant propre à cette matière — arabe, anglais. Vide, c'est le titulaire de la classe qui saisit.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='staff.teacher'),
        ),
    ]
