# Generated by Django 5.2.7 on 2026-07-29 16:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nom')),
                ('level', models.CharField(choices=[('PRESCHOOL', 'Préscolaire'), ('PRIMARY', 'Élémentaire')], max_length=20, verbose_name='cycle')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage, de la garderie au CM2.", verbose_name='rang')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='capacité')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'classe',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom de famille')),
                ('primary_contact', models.CharField(max_length=150, verbose_name='contact principal')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'famille',
                'verbose_name_plural': 'familles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="frais d'inscription")),
                ('monthly_tuition', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mensualité')),
                ('monthly_canteen', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantine mensuelle')),
                ('monthly_reinforcement', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='renforcement mensuel')),
                ('uniform_fee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='uniforme')),
                ('insurance_fee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='assurance')),
                ('ape_fee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cotisation APE')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='students.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'grille tarifaire',
                'verbose_name_plural': 'grilles tarifaires',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('parent_name', models.CharField(blank=True, max_length=150, verbose_name='parent / tuteur')),
                ('parent_phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone du parent')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='email du parent')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name="date d'inscription")),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('TRANSFERRED', 'Transféré'), ('EXPELLED', 'Exclu'), ('DROPPED', 'Abandon'), ('GRADUATED', 'Diplômé')], default='ACTIVE', max_length=20, verbose_name='statut')),
                ('status_effective_date', models.DateField(blank=True, null=True, verbose_name="date d'effet du statut")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.classroom', verbose_name='classe')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.family')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
            ],
            options={
                'verbose_name': 'élève',
                'verbose_name_plural': 'élèves',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Dernier jour du mois concerné.', verbose_name='période')),
                ('tuition', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='mensualité')),
                ('canteen', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantine')),
                ('reinforcement', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='renforcement')),
                ('uniform', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='uniforme')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='date de paiement')),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('TRANSFER', 'Virement'), ('CHECK', 'Chèque')], default='CASH', max_length=20, verbose_name='moyen')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('received_by', models.CharField(blank=True, max_length=150, verbose_name='encaissé par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_payments', to='core.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='students.student')),
            ],
            options={
                'verbose_name': 'encaissement mensuel',
                'verbose_name_plural': 'encaissements mensuels',
                'ordering': ['period', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_paid', models.BooleanField(default=False, verbose_name='inscription réglée')),
                ('registration_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant inscription')),
                ('uniform_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='uniforme')),
                ('insurance_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='assurance')),
                ('ape_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='APE')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='date de règlement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(help_text="Classe à l'inscription — l'élève peut changer de classe ensuite.", on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'inscription',
                'ordering': ['-year__start_date', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PERCENT', 'Pourcentage'), ('FIXED', 'Montant fixe'), ('FULL', 'Bourse totale')], max_length=10, verbose_name='type')),
                ('scope', models.CharField(choices=[('REGISTRATION', 'Inscription'), ('TUITION', 'Mensualité'), ('BOTH', 'Inscription et mensualité')], default='BOTH', max_length=15, verbose_name='portée')),
                ('value', models.PositiveIntegerField(default=0, help_text='Pourcentage de 0 à 100, ou montant en devise.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='valeur')),
                ('reason', models.CharField(max_length=255, verbose_name='motif')),
                ('approved_by', models.CharField(max_length=150, verbose_name='approuvé par')),
                ('approved_at', models.DateField(blank=True, null=True, verbose_name="date d'approbation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.schoolyear')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='students.family')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='students.student')),
            ],
            options={
                'verbose_name': 'réduction',
                'verbose_name_plural': 'réductions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name="date d'effet")),
                ('is_repeat', models.BooleanField(default=False, verbose_name='redoublement')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolyear')),
                ('from_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.classroom')),
                ('to_classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='students.student')),
            ],
            options={
                'verbose_name': 'changement de classe',
                'verbose_name_plural': 'changements de classe',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_class_per_school'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.UniqueConstraint(fields=('classroom', 'year'), name='unique_fee_schedule_per_class_year'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'classroom', 'status'], name='students_st_school__d82893_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlypayment',
            index=models.Index(fields=['school', 'year', 'period'], name='students_mo_school__7d061d_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlypayment',
            constraint=models.UniqueConstraint(fields=('student', 'period'), name='unique_payment_per_student_period'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school', 'year', 'classroom'], name='students_en_school__6203a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'year'), name='unique_enrollment_per_student_year'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', True), ('student__isnull', False)), models.Q(('family__isnull', False), ('student__isnull', True)), _connector='OR'), name='discount_targets_student_xor_family'),
        ),
    ]
