# Generated by Django 5.2.7 on 2026-07-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeschedule',
            options={'ordering': ['classroom__order'], 'verbose_name': 'grille tarifaire', 'verbose_name_plural': 'grilles tarifaires'},
        ),
    ]
