# Generated by Django 5.2.7 on 2026-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_feeschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='phone_e164',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, verbose_name='téléphone normalisé'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone_e164',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Forme « 221XXXXXXXXX », dérivée de parent_phone. Sert au rattachement du portail parent : les numéros sont saisis dans des formats trop variés pour être comparés tels quels.', max_length=20, verbose_name='téléphone normalisé'),
        ),
    ]
