# Generated by Django 5.2.7 on 2026-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_matricule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.CharField(choices=[('SOCIAL', 'Bourse sociale'), ('SIBLING', 'Réduction fratrie'), ('STAFF', 'Enfant du personnel'), ('MERIT', 'Bourse au mérite'), ('OTHER', 'Autre')], default='SOCIAL', max_length=15, verbose_name='nature'),
        ),
    ]
