# Generated by Django 5.2.7 on 2026-08-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teacher_address_teacher_email_and_more'),
        ('students', '0007_renumber_class_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Enseignant de la classe. Il saisit les notes de toutes ses matières.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='staff.teacher', verbose_name='titulaire'),
        ),
    ]
