# Generated by Django 5.2.7 on 2026-08-12 11:51

import django.db.models.deletion
from django.db import migrations, models


def carry_teachers_to_the_current_year(apps, schema_editor):
    """Reporte le titulaire porté par la classe vers l'affectation annuelle.

    Le champ était sur la classe, donc sans année : on le rattache à l'année
    courante de chaque établissement. Supprimer le champ sans ce report perdrait
    les affectations déjà saisies, sans que personne s'en aperçoive avant la
    première saisie de notes refusée.
    """
    ClassRoom = apps.get_model("students", "ClassRoom")
    ClassTeacher = apps.get_model("students", "ClassTeacher")
    SchoolYear = apps.get_model("core", "SchoolYear")

    for classroom in ClassRoom.objects.exclude(teacher__isnull=True):
        year = SchoolYear.objects.filter(
            school_id=classroom.school_id, is_current=True
        ).first()
        if year is None:
            continue
        ClassTeacher.objects.get_or_create(
            classroom_id=classroom.id,
            year_id=year.id,
            defaults={"school_id": classroom.school_id, "teacher_id": classroom.teacher_id},
        )


def noop(apps, schema_editor):
    """Sans retour : le champ retiré ne peut pas être reconstitué par année."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_photo_loginsession_passwordresettoken'),
        ('staff', '0003_teacher_address_teacher_email_and_more'),
        ('students', '0008_classroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='confirmed_at',
            field=models.DateField(blank=True, null=True, verbose_name='date de confirmation'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_repeat',
            field=models.BooleanField(default=False, verbose_name='redoublement'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='promoted_from',
            field=models.ForeignKey(blank=True, help_text="Classe de l'année précédente, quand l'inscription vient d'un passage.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.classroom'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('WITHDRAWN', 'Retirée')], default='CONFIRMED', help_text="En attente tant que la réinscription n'est pas confirmée.", max_length=20, verbose_name='état'),
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='students.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='staff.teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'titulaire de classe',
                'verbose_name_plural': 'titulaires de classe',
                'ordering': ['classroom__order'],
                'constraints': [models.UniqueConstraint(fields=('classroom', 'year'), name='one_teacher_per_class_and_year')],
            },
        ),
            migrations.RunPython(carry_teachers_to_the_current_year, noop),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
    ]
