# Generated by Django 5.2.7 on 2026-07-29 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_user_options'),
        ('students', '0003_family_phone_e164_student_parent_phone_e164'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'événement Wave',
                'verbose_name_plural': 'événements Wave',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('TUITION', 'Mensualité'), ('REGISTRATION', 'Inscription')], default='TUITION', max_length=15)),
                ('period', models.DateField(blank=True, help_text='Fin de mois visée, pour une mensualité.', null=True, verbose_name='période')),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant')),
                ('method', models.CharField(choices=[('WAVE', 'Wave'), ('CASH', 'Espèces'), ('ORANGE_MONEY', 'Orange Money'), ('TRANSFER', 'Virement'), ('CHECK', 'Chèque')], max_length=20, verbose_name='moyen')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCEEDED', 'Confirmé'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=12)),
                ('reference', models.CharField(help_text='Transmise au prestataire comme `client_reference`.', max_length=64, unique=True, verbose_name='référence interne')),
                ('provider_session_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('provider_payment_id', models.CharField(blank=True, max_length=128)),
                ('checkout_url', models.URLField(blank=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('simulated', models.BooleanField(default=False, help_text="Vrai si le prestataire n'était pas configuré. Ces transactions ne doivent jamais être prises pour des encaissements réels.", verbose_name='simulé')),
                ('error', models.TextField(blank=True)),
                ('received_by', models.CharField(blank=True, max_length=150, verbose_name='encaissé par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('monthly_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='students.monthlypayment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school', verbose_name='établissement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='students.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.schoolyear')),
            ],
            options={
                'verbose_name': 'transaction de paiement',
                'verbose_name_plural': 'transactions de paiement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status', 'method'], name='payments_pa_school__407a41_idx'), models.Index(fields=['school', 'student', 'year'], name='payments_pa_school__e1802d_idx')],
            },
        ),
    ]
