# Generated by Django 5.2.7 on 2026-07-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('students', '0004_backfill_normalized_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='monthly_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='students.monthlypayment'),
        ),
    ]
